server:
  port: 8788

spring:
  datasource:
    druid:
      url: "jdbc:mysql://114.55.167.88:3306/team"
      username: root
      password: root

rocketmq:
  name-server:
  producer:
    group: member-group