server:
  port: 8717

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: admin
  cloud:
    nacos:
      discovery:
        server-addr: "114.55.167.88:8848"



