server:
  port: 8867
  servlet:
    context-path: /api

spring:
  application:
    name: "dubbo-pay-customer-m"
  profiles:
    active: dubbo

  cloud:
    nacos:
      discovery:
        server-addr: "114.55.167.88:8848"
        namespace: "public"

